# Generated by Django 4.0.4 on 2022-04-14 21:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_festival_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='festival',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
