# Generated by Django 4.0.4 on 2022-04-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0005_remove_festival_hotel_festival_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='festivals.festival'),
        ),
    ]
