# Generated by Django 4.0.4 on 2022-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0007_festival_lat_festival_long_hotel_lat_hotel_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
