# Generated by Django 4.0.4 on 2022-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0009_attending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attending',
            old_name='price_range',
            new_name='price_max',
        ),
        migrations.AddField(
            model_name='attending',
            name='price_min',
            field=models.FloatField(null=True),
        ),
    ]
