# Generated by Django 4.0.4 on 2022-04-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0011_grouptrip_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptrip',
            name='Festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_trip', to='festivals.festival'),
        ),
        migrations.AddField(
            model_name='grouptrip',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_trip', to='festivals.hotel'),
        ),
    ]
