# Generated by Django 4.0.4 on 2022-04-19 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festivals', '0012_grouptrip_festival_grouptrip_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attending',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending', to='festivals.festival'),
        ),
        migrations.AlterField(
            model_name='attending',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
