# Generated by Django 4.0.4 on 2022-04-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0014_alter_attending_festival_alter_attending_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attending',
        ),
    ]
