# Generated by Django 4.0.4 on 2022-04-21 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festivals', '0016_rename_destinationuserid_message_destination_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='destination_user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='source_user_id',
        ),
        migrations.AddField(
            model_name='message',
            name='destination_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_user_message', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='source_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_user_message', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
