# Generated by Django 4.0.4 on 2022-04-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0019_alter_message_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='location',
            field=models.CharField(choices=[('All', 'All'), ('Croatia', 'Croatia'), ('France', 'France'), ('Germany', 'Germany'), ('Hungary', 'Hungary'), ('Malta', 'Malta'), ('Mexico', 'Mexico'), ('Netherlands', 'Netherlands'), ('Spain', 'Spain')], default='All', max_length=20),
        ),
    ]
